### ISSUE TITLE
06_objects - assert when calling modulename.MyObject

### ISSUE THREAD

**Issue by pconstr** [kkaefer/node-cpp-modules#2]
in 06_objects/run.js , if I change:

``` javascript
var obj = new modulename.MyObject(42);
```

to:

``` javascript
var obj = modulename.MyObject(42);
```

I get:

```
Assertion failed: (handle->InternalFieldCount() > 0), function Wrap, file ../src/node_object_wrap.h, line 62.
```

naturally, this is not the intended usage, but a Javascript error would be nicer than a c++ assertion failure

**Comment by kkaefer** [comment]
Thanks for catching this!

**Comment by pconstr** [comment]
that was quick :)
Thank you for sharing. I'm new to node and v8, and I've found your guide very useful.
