### ISSUE TITLE
question: what's the different with eio_req and uv_work_t ?

### ISSUE THREAD

**Issue by guileen** [kkaefer/node-cpp-modules#3]
I see your node-blend, and it use a eio_req instead what you presentation said uv_work_t, I want to know what's the different between them.

Thanks a lot.

**Comment by kkaefer** [comment]
`eio_req` is the old API up to node 0.4. If you code modules for node 0.6+, you'll have to use [libuv's](https://github.com/joyent/libuv) `uv_*` types/functions.

**Comment by guileen** [comment]
Thank you for explain.
