### ISSUE TITLE
baton.request?

### ISSUE THREAD

**Issue by juliangruber** [kkaefer/node-cpp-modules#6]
Why assign the baton to baton.request when you can also assign the baton to you uv_workt_t request? Or is this just convention?

**Comment by kkaefer** [comment]
Are you referring to `baton->request.data = baton;`? If so, this is required because the async function only gets a reference to the `uv_work_t` struct, but we need to recover the pointer to the actual baton which contains other data like parameters to the async work request.

**Comment by juliangruber** [comment]
you could also do

``` c
uv_work_t req;

Baton* baton = new Baton();
/* ... */

req->data = baton;

uv_queue_work(req, ..., ...);
```

See https://github.com/joyent/node/wiki/How-to-migrate-from-eio_custom-to-uv_queue_work

As both work that's propably just convention I guess...

**Comment by kkaefer** [comment]
You're right. I changed the example to use the simplified version (though now you have to make sure you delete both the request and the baton). The previous way was a leftover construct from the libeio days of node 0.4

**Comment by kkaefer** [comment]
Committed in 0f7ee630ed6b6ce4aceed3c41e5146c7e8d9ce80.
